name: Goblin Seeker Bot

on:
  schedule:
    - cron: '0 * * * *' # Every hour
  workflow_dispatch: # Manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4 # Updated to v4

      - name: Set up Python environment
        uses: actions/setup-python@v5 # Updated to v5
        with:
          python-version: '3.11'

      - name: Install required libraries
        run: |
          pip install -r requirements.txt

      - name: Execute the bot script
        env:
          X_CLIENT_ID: ${{ secrets.X_CLIENT_ID }}
          X_CLIENT_SECRET: ${{ secrets.X_CLIENT_SECRET }}
          X_ACCESS_TOKEN: ${{ secrets.X_ACCESS_TOKEN }}
          X_REFRESH_TOKEN: ${{ secrets.X_REFRESH_TOKEN }}
        run: python bot.py
        
